export const key = 'paymentAndBilling';

export const CHANGE_RATE = 'PAYMENT_FORM_CHANGE_RATE';
export const CHANGE_BILLING_TYPE = 'PAYMENT_FORM_CHANGE_BILLING_TYPE';
export const CHANGE_COMPANY_DETAILS = 'PAYMENT_FORM_CHANGE_COMPANY_DETAILS';
export const CHANGE_PAY_TYPE = 'PAYMENT_FORM_CHANGE_PAY_TYPE';
export const CHANGE_BANK_PAY_DETAILS = 'PAYMENT_FORM_CHANGE_BANK_PAY_DETAILS';
export const CHANGE_PAYPAL_DETAILS = 'PAYMENT_FORM_CHANGE_PAYPAL_DETAILS';

export const SAVE_FOR_LATER = 'PAYMENT_FORM_SAVE_FOR_LATER';

export const EDIT_BILLING = 'PAYMENT_FORM_EDIT_BILLING';
export const EDIT_PAYMENT = 'PAYMENT_FORM_EDIT_PAYMENT';
export const PASSWORD = 'PASSWORD';
