export const SET_PROFESSIONAL_DATA = 'SET_PROFESSIONAL_DATA';
export const RESET_DATA = 'RESET_DATA';

export const CHANGE_LINKEDIN_PROFILE = 'CHANGE_LINKEDIN_PROFILE';
export const CHANGE_GITHUB_PROFILE = 'CHANGE_GITHUB_PROFILE';
export const CHANGE_STACKOVERFLOW_PROFILE = 'CHANGE_STACKOVERFLOW_PROFILE';

export const CHANGE_DRIBBBLE_PROFILE = 'CHANGE_DRIBBBLE_PROFILE';
export const CHANGE_BEHANCE_PROFILE = 'CHANGE_BEHANCE_PROFILE';
export const CHANGE_PERSONAL_PROFILE = 'CHANGE_PERSONAL_PROFILE';
export const CHANGE_PRIMARY_ROLE = 'CHANGE_PRIMARY_ROLE';
export const CHANGE_EXPERIENCE = 'CHANGE_EXPERIENCE';
export const CHANGE_SKILLS = 'CHANGE_SKILLS';

export const SAVE_FOR_LATER = 'PROFESSIONAL_SAVE_FOR_LATER';
export const EDIT_PROFESSIONAL_URL = 'PROFESSIONAL_EDIT_PROFESSIONAL_URL';
export const EDIT_PROFESSIONAL_SKILLS = 'PROFESSIONAL_EDIT_PROFESSIONAL_SKILLS';

export const RESET_PROFESSIONAL_DETAILS = 'RESET_PROFESSIONAL_DETAILS';
export const SUBMIT_PROFESSIONAL_FORM = 'SUBMIT_PROFESSIONAL_FORM';

export const key = 'professionalForm';
