import {
  TALENT,
  CLIENT,
  ADMIN,
  projectsIcon,
  userIcon,
  calendarWithTimeIcon,
  quotesIcon,
  dollarIcon,
  clientsIcon,
  dashboardIcon,
  textFileIcon,
  builidingIcon,
  searchJobsIcon,
} from 'containers/App/constants';

export const clientNavPages = [
  {
    title: 'Dashboard',
    pathName: `${CLIENT}/dashboard`,
    icon: dashboardIcon,
    paths: ['/', '/client', '/client/', `${CLIENT}/dashboard`, `${CLIENT}/dashboard/`],
    childPaths: [],
    isBadgeConfig: false,
  },
  {
    title: 'Job Briefs',
    pathName: `${CLIENT}/job-briefs`,
    icon: textFileIcon,
    paths: [`${CLIENT}/job-briefs`, `${CLIENT}/job-briefs/`],
    childPaths: [`${CLIENT}/brief-detail/`, `${CLIENT}/brief-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Projects',
    pathName: `${CLIENT}/projects`,
    icon: projectsIcon,
    paths: [`${CLIENT}/projects`, `${CLIENT}/projects/`],
    childPaths: [`${CLIENT}/project-detail/`, `${CLIENT}/project-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Talents',
    pathName: `${CLIENT}/talents`,
    icon: clientsIcon,
    paths: [`${CLIENT}/talents`, `${CLIENT}/talents`],
    childPaths: [],
    isBadgeConfig: false,
  },
  {
    title: 'Timesheets',
    pathName: `${CLIENT}/timesheets`,
    icon: calendarWithTimeIcon,
    paths: [`${CLIENT}/timesheets`, `${CLIENT}/timesheets`],
    childPaths: [],
    isBadgeConfig: true,
  },
  /* For Future use
  {
    title: 'Bill',
    pathName: `${CLIENT}/billing`,
    icon: billIcon,
    paths: [`${CLIENT}/billing`, `${CLIENT}/billing`],
    childPaths: [],
    isBadgeConfig: false,
  },
  {
    title: 'Contracts',
    pathName: `${CLIENT}/contracts`,
    icon: contractIcon,
    paths: [`${CLIENT}/contracts`, `${CLIENT}/contracts`],
    childPaths: [],
    isBadgeConfig: false,
  },
  {
    title: 'Payments',
    pathName: `${CLIENT}/payments`,
    icon: paymentIcon,
    paths: [`${CLIENT}/payments`, `${CLIENT}/payments`],
    childPaths: [],
    isBadgeConfig: false,
  },
  */
];

export const adminNavPages = [
  {
    title: 'Dashboard',
    pathName: `${ADMIN}/dashboard`,
    icon: dashboardIcon,
    paths: ['/', '/admin', '/admin/', `${ADMIN}/dashboard`, `${ADMIN}/dashboard/`],
    childPaths: [],
    isBadgeConfig: false,
  },
  {
    title: 'Projects',
    pathName: `${ADMIN}/projects`,
    icon: projectsIcon,
    paths: [`${ADMIN}/projects`, `${ADMIN}/projects`],
    childPaths: [`${ADMIN}/project-detail/`, `${ADMIN}/project-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Job Briefs',
    pathName: `${ADMIN}/job-briefs`,
    icon: textFileIcon,
    paths: [`${ADMIN}/job-briefs`, `${ADMIN}/job-briefs`],
    childPaths: [`${ADMIN}/brief-detail/`, `${ADMIN}/brief-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Interviews',
    pathName: `${ADMIN}/interviews`,
    icon: calendarWithTimeIcon,
    paths: [`${ADMIN}/interviews`, `${ADMIN}/interviews`],
    childPaths: [`${ADMIN}/interview-detail/`, `${ADMIN}/interview-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Quotes',
    pathName: `${ADMIN}/quotes`,
    icon: quotesIcon,
    paths: [`${ADMIN}/quotes`, `${ADMIN}/quotes`],
    childPaths: [`${ADMIN}/quote-detail/`, `${ADMIN}/quote-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Talents',
    pathName: `${ADMIN}/talents`,
    icon: clientsIcon,
    paths: [`${ADMIN}/talents`, `${ADMIN}/talents`],
    childPaths: [`${ADMIN}/talent-profile/`, `${ADMIN}/talent-profile`],
    isBadgeConfig: false,
  },
  {
    title: 'Timesheets',
    pathName: `${ADMIN}/timesheets`,
    icon: calendarWithTimeIcon,
    paths: [`${ADMIN}/timesheets`, `${ADMIN}/timesheets`],
    childPaths: [],
    isBadgeConfig: false,
  },
  {
    title: 'Clients',
    pathName: `${ADMIN}/clients`,
    icon: userIcon,
    paths: [`${ADMIN}/clients`, `${ADMIN}/clients`],
    childPaths: [`${ADMIN}/client-detail/`, `${ADMIN}/client-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Agencies',
    pathName: `${ADMIN}/agencies`,
    icon: builidingIcon,
    paths: [`${ADMIN}/agencies`, `${ADMIN}/agencies`],
    childPaths: [`${ADMIN}/agency-detail/`, `${ADMIN}/agency-detail`],
    isBadgeConfig: false,
  },
  {
    title: 'Referrals',
    pathName: `${ADMIN}/referrals`,
    icon: dollarIcon,
    paths: [`${ADMIN}/referrals`, `${ADMIN}/referrals`],
    childPaths: [],
    isBadgeConfig: false,
  },
];

export const talentNavPages = [
  {
    title: 'Dashboard',
    pathName: `${TALENT}/dashboard`,
    icon: dashboardIcon,
    paths: ['/', '/talent', '/talent/', `${TALENT}/dashboard`, `${TALENT}/dashboard/`],
    isBadgeConfig: false,
  },
  {
    title: 'Jobs',
    pathName: `${TALENT}/job-briefs`,
    icon: searchJobsIcon,
    paths: [`${TALENT}/job-briefs`, `${TALENT}/job-briefs`],
    isBadgeConfig: true,
  },
  {
    title: 'Projects',
    pathName: `${TALENT}/my-projects`,
    icon: projectsIcon,
    paths: [`${TALENT}/my-projects`, `${TALENT}/my-projects`],
    isBadgeConfig: false,
  },
  {
    title: 'Timesheets',
    pathName: `${TALENT}/timesheets`,
    icon: calendarWithTimeIcon,
    paths: [`${TALENT}/timesheets`, `${TALENT}/timesheets`],
    isBadgeConfig: false,
  },
  /* For Future use
  {
    title: 'Invoices',
    pathName: `${TALENT}/invoices`,
    icon: billIcon,
    paths: [`${TALENT}/invoices`, `${TALENT}/invoices`],
    isBadgeConfig: false,
  },
  {
    title: 'Knowledge base',
    pathName: `${TALENT}/knowledge-base`,
    icon: booksIcon,
    paths: [`${TALENT}/knowledge-base`, `${TALENT}/knowledge-base`],
    isBadgeConfig: false,
  },
  {
    title: 'Community',
    pathName: `${TALENT}/community`,
    icon: communityIcon,
    paths: [`${TALENT}/community`, `${TALENT}/community`],
    isBadgeConfig: false,
  },
  {
    title: 'Career Paths',
    pathName: `${TALENT}/career-paths`,
    icon: briefcaseIcon,
    paths: [`${TALENT}/career-paths`, `${TALENT}/career-paths`],
    isBadgeConfig: false,
  },
  {
    title: 'Learning Development',
    pathName: `${TALENT}/learning-development`,
    icon: learningIcon,
    paths: [`${TALENT}/learning-development`, `${TALENT}/learning-development`],
    isBadgeConfig: false,
  },
  {
    title: 'Perks',
    pathName: `${TALENT}/perks`,
    icon: perksIcon,
    paths: [`${TALENT}/perks`, `${TALENT}/perks`],
    isBadgeConfig: false,
  },
  {
    title: 'Wellbeing',
    pathName: `${TALENT}/wellbeing`,
    icon: heartIcon,
    paths: [`${TALENT}/wellbeing`, `${TALENT}/wellbeing`],
    isBadgeConfig: false,
  },
  */
];
